"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 13:04:48.314165
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import perseus_common.db


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_records',
    sa.Column('seq', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('producer', sa.String(length=64), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=True),
    sa.Column('subject_id', sa.String(length=64), nullable=True),
    sa.Column('occurred_at', perseus_common.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('recorded_at', perseus_common.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('record_json', sa.Text(), nullable=False),
    sa.Column('prev_hash', sa.String(length=64), nullable=False),
    sa.Column('hash', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('seq', name=op.f('pk_audit_records')),
    sa.UniqueConstraint('event_id', name=op.f('uq_audit_records_event_id')),
    sa.UniqueConstraint('hash', name=op.f('uq_audit_records_hash'))
    )
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_records_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_records_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_records_occurred_at'), ['occurred_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_records_subject_id'), ['subject_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_records_subject_id'))
        batch_op.drop_index(batch_op.f('ix_audit_records_occurred_at'))
        batch_op.drop_index(batch_op.f('ix_audit_records_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_records_actor_id'))

    op.drop_table('audit_records')
    # ### end Alembic commands ###
