"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 13:04:45.640565
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import perseus_common.db


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('owner_id', sa.Uuid(), nullable=False),
    sa.Column('account_number', sa.String(length=10), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=True),
    sa.Column('frozen_reason', sa.String(length=200), nullable=True),
    sa.Column('created_at', perseus_common.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('updated_at', perseus_common.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('closed_at', perseus_common.db.UTCDateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_accounts')),
    sa.UniqueConstraint('account_number', name=op.f('uq_accounts_account_number'))
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_owner_id'), ['owner_id'], unique=False)

    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('envelope', sa.Text(), nullable=False),
    sa.Column('created_at', perseus_common.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('published_at', perseus_common.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_published_at'), ['published_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_events_published_at'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_created_at'))

    op.drop_table('outbox_events')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_owner_id'))

    op.drop_table('accounts')
    # ### end Alembic commands ###
