"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-10-06 13:04:46.369989
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

import perseus_common.db


revision: str = '0001'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balances',
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance_minor', sa.BigInteger(), nullable=False),
    sa.Column('allow_negative', sa.Boolean(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_at', perseus_common.db.UTCDateTime(timezone=True), nullable=False),
    sa.CheckConstraint('allow_negative OR balance_minor >= 0', name=op.f('ck_balances_non_negative')),
    sa.PrimaryKeyConstraint('account_id', name=op.f('pk_balances'))
    )
    op.create_table('idempotency_keys',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('principal_id', sa.String(length=64), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('request_hash', sa.String(length=64), nullable=False),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('created_at', perseus_common.db.UTCDateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_idempotency_keys')),
    sa.UniqueConstraint('principal_id', 'key', name='principal_key')
    )
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_idempotency_keys_created_at'), ['created_at'], unique=False)

    op.create_table('outbox_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('envelope', sa.Text(), nullable=False),
    sa.Column('created_at', perseus_common.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('published_at', perseus_common.db.UTCDateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_outbox_events'))
    )
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outbox_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_outbox_events_published_at'), ['published_at'], unique=False)

    op.create_table('transactions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('source_account_id', sa.Uuid(), nullable=False),
    sa.Column('destination_account_id', sa.Uuid(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('description', sa.String(length=140), nullable=True),
    sa.Column('initiated_by', sa.String(length=64), nullable=False),
    sa.Column('source_owner_id', sa.String(length=64), nullable=True),
    sa.Column('destination_owner_id', sa.String(length=64), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('risk_decision', sa.String(length=10), nullable=True),
    sa.Column('assessment_id', sa.Uuid(), nullable=True),
    sa.Column('failure_reason', sa.String(length=50), nullable=True),
    sa.Column('reviewed_by', sa.String(length=64), nullable=True),
    sa.Column('created_at', perseus_common.db.UTCDateTime(timezone=True), nullable=False),
    sa.Column('completed_at', perseus_common.db.UTCDateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount_minor > 0', name=op.f('ck_transactions_positive_amount')),
    sa.CheckConstraint('source_account_id <> destination_account_id', name=op.f('ck_transactions_distinct_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_transactions'))
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_destination_account_id'), ['destination_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_initiated_by'), ['initiated_by'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_source_account_id'), ['source_account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_status'), ['status'], unique=False)

    op.create_table('entries',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('transaction_id', sa.Uuid(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('amount_minor', sa.BigInteger(), nullable=False),
    sa.Column('balance_after', sa.BigInteger(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('created_at', perseus_common.db.UTCDateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_entries_transaction_id_transactions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entries'))
    )
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.create_index('ix_entries_account_created', ['account_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_entries_transaction_id'), ['transaction_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entries_transaction_id'))
        batch_op.drop_index('ix_entries_account_created')

    op.drop_table('entries')
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_status'))
        batch_op.drop_index(batch_op.f('ix_transactions_source_account_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_initiated_by'))
        batch_op.drop_index(batch_op.f('ix_transactions_destination_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('outbox_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outbox_events_published_at'))
        batch_op.drop_index(batch_op.f('ix_outbox_events_created_at'))

    op.drop_table('outbox_events')
    with op.batch_alter_table('idempotency_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_idempotency_keys_created_at'))

    op.drop_table('idempotency_keys')
    op.drop_table('balances')
    # ### end Alembic commands ###
