"""Generate the git-ignored ``.env`` file: all secrets plus local-development settings.

Usage:  uv run python scripts/generate_secrets.py [--force]

Docker Compose reads ``.env`` automatically and injects the values as environment
variables. The file is written with mode 0600. For production, change the settings in the
"Deployment settings" block (domain, SMTP relay, ...) as documented in ``.env.example``.
TLS certificates are not secrets managed here: certbot issues them (see README).
"""

from __future__ import annotations

import argparse
import hashlib
import json
import secrets
import sys
from pathlib import Path

from cryptography.fernet import Fernet
from cryptography.hazmat.primitives import serialization
from cryptography.hazmat.primitives.asymmetric import rsa

SERVICES = ("auth", "accounts", "ledger", "fraud", "notifications", "audit")
# Which internal APIs each calling service may use (OAuth2 client-credentials scopes).
SERVICE_CLIENT_SCOPES = {
    "ledger-service": ["accounts:read", "fraud:assess"],
    "accounts-service": ["ledger:balance:read"],
}


def _pem_key(key: rsa.RSAPrivateKey) -> bytes:
    return key.private_bytes(
        serialization.Encoding.PEM,
        serialization.PrivateFormat.PKCS8,
        serialization.NoEncryption(),
    )


def build_secrets() -> dict[str, str]:
    values: dict[str, str] = {
        "POSTGRES_PASSWORD": secrets.token_urlsafe(32),
        "REDIS_PASSWORD": secrets.token_urlsafe(32),
        "EVENT_SIGNING_KEY": secrets.token_urlsafe(48),
        "MFA_ENCRYPTION_KEY": Fernet.generate_key().decode(),
        "JWT_PRIVATE_KEY": _pem_key(
            rsa.generate_private_key(public_exponent=65537, key_size=3072)
        ).decode(),
    }
    for service in SERVICES:
        values[f"{service.upper()}_DB_MIGRATOR_PASSWORD"] = secrets.token_urlsafe(32)
        values[f"{service.upper()}_DB_APP_PASSWORD"] = secrets.token_urlsafe(32)

    registry: dict[str, dict[str, object]] = {}
    for client_id, scopes in SERVICE_CLIENT_SCOPES.items():
        secret = secrets.token_urlsafe(48)
        values[f"{client_id.split('-')[0].upper()}_CLIENT_SECRET"] = secret
        registry[client_id] = {
            "secret_sha256": hashlib.sha256(secret.encode()).hexdigest(),
            "scopes": scopes,
        }
    values["SERVICE_CLIENTS"] = json.dumps(registry, separators=(",", ":"))
    return values


# Non-secret settings, defaulting to local development. See .env.example for production.
LOCAL_SETTINGS = {
    "ENVIRONMENT": "development",
    "DOMAIN": "localhost",
    "GATEWAY_BIND": "127.0.0.1",
    "HTTP_PORT": "8080",
    "HTTPS_PORT": "8443",
    "LETSENCRYPT_DIR": "./letsencrypt",
    "CERTBOT_WEBROOT": "./certbot-www",
    "SMTP_HOST": "mailpit",
    "SMTP_PORT": "1025",
    "SMTP_STARTTLS": "false",
    "SMTP_USERNAME": "",
    "SMTP_PASSWORD": "",
    "MAIL_FROM": "Perseus Finance <no-reply@perseus.local>",
}


def render_env(values: dict[str, str]) -> str:
    lines = [
        "# Generated by scripts/generate_secrets.py - DO NOT COMMIT (listed in .gitignore).",
        "# Rotate every secret with: uv run python scripts/generate_secrets.py --force",
        "",
        "# --- Deployment settings (local development defaults; see .env.example) ---",
        *(f"{name}='{value}'" for name, value in LOCAL_SETTINGS.items()),
        "",
        "# --- Secrets ---",
    ]
    for name, value in values.items():
        if "\n" in value:  # PEM: one line, escaped newlines, double quotes
            lines.append(f'{name}="{value.strip().replace(chr(10), chr(92) + "n")}"')
        else:  # literal single-quoted value (JSON contains double quotes)
            lines.append(f"{name}='{value}'")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    root = Path(__file__).resolve().parent.parent
    parser.add_argument("--force", action="store_true", help="overwrite (rotate) existing secrets")
    parser.add_argument("--env-file", default=root / ".env", type=Path)
    args = parser.parse_args()

    env_file: Path = args.env_file
    if env_file.exists() and not args.force:
        print(f"{env_file} already exists; use --force to rotate every secret.", file=sys.stderr)
        return 1
    values = build_secrets()
    env_file.touch(mode=0o600, exist_ok=True)
    env_file.chmod(0o600)
    env_file.write_text(render_env(values))
    print(f"Wrote {env_file} (mode 600)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
